DjangoTeamApplication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home_page'),
    path('admin/', admin.site.urls),
    path('team/', include('TeamApplication.urls'))
]

TeamApplication/urls.py
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    # ex: /team/
    path('', views.TeamMemberListView.as_view(), name='index'),
    # /team/add
    path('add/', views.TeamMemberAddView.as_view(), name='add'),
    # ex: /team/5/
    path('<int:pk>/', views.TeamMemberUpdateView.as_view(), name='detail'),
    # ex: /team/5/delete
    path('<int:pk>/delete/', views.TeamMemberDeleteView.as_view(), name='delete'),
]

TeamApplication/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models

import re

phone_regex = re.compile(r'[0-9]{3}-[0-9]{3}-[0-9]{4}$')

User = get_user_model()


class TeamMemberRoles(models.TextChoices):
    REGULAR = "regular", _('Regular - Can\'t delete members')
    ADMIN = "admin", _('Admin - Can delete members')


def validate_phone_number(value):
    if phone_regex.fullmatch(value) is None:
        raise ValidationError(
            _('%(value)s is not a phone number'),
            params={'value': value},
        )


class TeamMember(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email_id = models.EmailField(max_length=64)
    mobile_number = models.CharField(
        max_length=15,
        help_text="Please use the following format: <em>XXX-XXX-XXXX</em>.",
        validators=[validate_phone_number]
    )
    role = models.CharField(max_length=10, choices=TeamMemberRoles.choices, default=TeamMemberRoles.REGULAR)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def is_admin(self):
        return self.role == TeamMemberRoles.ADMIN

TeamApplication/forms.py
from django.forms import ModelForm
from . import models


class TeamMemberForm(ModelForm):
    class Meta:
        model = models.TeamMember
        exclude = ('user', )

DjangoTeamApplication/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

TeamApplication/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .models import TeamMember
from .forms import TeamMemberForm


class TeamMemberListView(LoginRequiredMixin, ListView):
    template_name = 'TeamApplication/TeamMember/list.html'
    model = TeamMember
    context_object_name = 'members'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TeamMemberAddView(LoginRequiredMixin, CreateView):
    template_name = 'TeamApplication/TeamMember/form.html'
    model = TeamMember
    form_class = TeamMemberForm
    success_url = reverse_lazy('team:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TeamMemberAddView, self).form_valid(form)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        kwargs['update_only'] = False
        context = super(TeamMemberAddView, self).get_context_data(**kwargs)
        return context


class TeamMemberUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'TeamApplication/TeamMember/form.html'
    model = TeamMember
    form_class = TeamMemberForm
    success_url = reverse_lazy('team:index')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        kwargs['update_only'] = True
        context = super(TeamMemberUpdateView, self).get_context_data(**kwargs)
        return context


class TeamMemberDeleteView(LoginRequiredMixin, DeleteView):
    model = TeamMember
    form_class = TeamMemberForm
    success_url = reverse_lazy('team:index')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

templates/TeamApplication/TeamMember/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block active_link %}nav-team{% endblock %}

{% block content %}
    {% if update_only %}
        <h3> Edit team member </h3>
        <h4><small class="text-muted">Edit contact info, location and role</small></h4>
    {% else %}
        <h3>Add a team member</h3>
        <h4><small class="text-muted">Set email, location and role</small></h4>
    {% endif %}
    <hr/>

    {% bootstrap_form_errors form %}
    <form method="post" style="display: inline;">{% csrf_token %}
        {% bootstrap_form form %}

        {% if update_only %}
            {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
        {% else %}
            {% bootstrap_button "Create" button_type="submit" button_class="btn-primary" %}
        {% endif %}
    </form>
    {% if update_only %}
        {% url 'team:delete' form.instance.pk as delete_url %}
        <form method="post" action="{{ delete_url }}" style="display: inline;">
            {% csrf_token %}
            {% bootstrap_button "Delete" button_type="submit" button_class="btn-danger" %}
        </form>
    {% endif %}
{% endblock %}

templates/TeamApplication/TeamMember/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block active_link %}nav-team{% endblock %}

{% block content %}
    {% url 'team:add' as add_url %}
    {% bootstrap_button "Add New" button_type="link" href=add_url button_class="btn-primary" %}

    <h3> Team Members </h3>
    <h4><small class="text-muted">You have {{ members|length }} team member(s).</small></h4>
    <hr/>

    {% for member in members %}
        <a href="{% url 'team:detail' member.id %}" style="text-decoration: none">
            <div style="display: flex; flex-direction: row; cursor: pointer">
                <div>
                    <img src="{% static 'img/account-circle.png' %}" alt="profile-pic">
                </div>
                <div>
                    {{ member.last_name }} {{ member.first_name }} {% if member.is_admin %} (admin) {% endif %} <br/>
                    <small class="text-muted">
                        {{ member.mobile_number }} <br/>
                        {{ member.email_id }}
                    </small>
                </div>
            </div>
        </a>
        <hr/>
    {% endfor %}
{% endblock %}

templates/base.html
{% extends 'bootstrap.html' %}

{% load bootstrap4 %}

{% block bootstrap4_before_content %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div style="color: darkred">TeamMemberApp</div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item nav-home">
                    <a class="nav-link" href="{% url 'home_page' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item nav-team">
                    <a class="nav-link" href="{% url 'team:index' %}">Your Team</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block bootstrap4_content %}
    <div class="container">
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

{% block bootstrap4_extra_script %}
    <script>
        $('nav').find('.{% block active_link%}{%endblock%}').addClass('active')
    </script>
{% endblock %}

templates/bootstrap.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% block bootstrap4_title %}{% block title %}TeamMember App{% endblock %}{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
{% endblock %}

{% block active_link %}nav-home{% endblock %}